-- MySQL Script generated by MySQL Workbench
-- Mon Oct 24 16:11:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema softia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema softia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `softia` DEFAULT CHARACTER SET utf8 ;
USE `softia` ;

-- -----------------------------------------------------
-- Table `softia`.`agreements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softia`.`agreements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `hours` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO agreements(name,hours)
VALUES
        ("Convention A", 7),
        ("Convention B", 2),
        ("Convention C", 9),
        ("Convention D", 0);

-- -----------------------------------------------------
-- Table `softia`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softia`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(48) NOT NULL,
  `lastname` VARCHAR(48) NULL,
  `email` VARCHAR(255) NULL,
  `agreement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_students_agreements1_idx` (`agreement_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_agreements1`
    FOREIGN KEY (`agreement_id`)
    REFERENCES `softia`.`agreements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO students (firstname,lastname,email,agreement_id)
VALUES
        ("Jeanette","Hills","jeanette.hills@mail.com",1),
        ("Cordell","Wolff","cordell.wolff@mail.com",2),
        ("Mason","Hartmann","mason.hartmann@mail.com",1),
        ("Ruth","Vandervort","ruth.vandervort@mail.com",1),
        ("Ike","Ernser","ike.ernser@mail.com",4),
        ("Eda","Mills","eda.mills@mail.com",1),
        ("Jada","Hackett","jada.hackett@mail.com",2),
        ("Celine","Tillman","celine.tillman@mail.com",3),
        ("Moses","Cronin","moses.cronin@mail.com",3),
        ("Meda","O'Kon","meda.o-kon@mail.de",4);

-- -----------------------------------------------------
-- Table `softia`.`certificates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softia`.`certificates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `student_id` INT NOT NULL,
  `agreement_id` INT NOT NULL,
  PRIMARY KEY (`id`, `student_id`, `agreement_id`),
  INDEX `fk_certificate_students_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_certificate_agreements1_idx` (`agreement_id` ASC) VISIBLE,
  CONSTRAINT `fk_certificate_students`
    FOREIGN KEY (`student_id`)
    REFERENCES `softia`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_certificate_agreements1`
    FOREIGN KEY (`agreement_id`)
    REFERENCES `softia`.`agreements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
